### ISSUE TITLE
Use an object for generateRandomColorRamp argument

### ISSUE THREAD

**Issue by caillou** [meodai/fettepalette#1]
As of now, `generateRandomColorRamp` has many default values:

```ts
export default function generateRandomColorRamp  (
  total:number,
  centerHue:number           = 0,
  hueCycle:number            = 0.3,
  offsetTint:number          = 0.1,
  offsetShade:number         = 0.1,
  curveAccent:number         = 0,
  tintShadeHueShift:number   = 0.1,
  curveMethod:curveMethod    = 'arc', 
  offsetCurveModTint:number  = 0.03,
  offsetCurveModShade:number = 0.03,
  minSaturationLight:vector2 = [0, 0],
  maxSaturationLight:vector2 = [1, 1]
):{
  light: hsx[],
  dark: hsx[],
  base: hsx[],
  all: hsx[]
} {}
```

If I want to modify just one of the default arguments, I need to list all the arguments prior to it, e.g. if I want a different value for `offsetShade`, I will have to call the function as follows:

```ts
generateRandomColorRamp(2, 0, .3, .1, .2)
```

Also, it is not obvious, what these values stand for, when reading the code.

The following API would be much more intuitive:

```ts
generateRandomColorRamp(2, {
  offsetShade: .2
})
```

**Comment by caillou** [comment]
The same applies to `hsv2hsl`, where only parts of the options are required. This is how you could solve this:

```ts
type HSX = [number, number, number];

export const hsv2hsl = (params: {
  h: number,
  s: number,
  v: number,
  l ?: number,
  m ?: number
}): HSX => {
  const {h, s, v} = params;
  const l = params.l || v - (v * s) / 2;
  const m = params.l || Math.min(l, 1 - l);
  
  // ...

};
```

**Comment by meodai** [comment]
@caillou I just had the same thought while using it thanks a lot! https://github.com/meodai/fettepalette/blob/main/src/index.ts#L125

Will also do it for the hsv2hsl function though
