### ISSUE TITLE
Fix index.js mess in package.json

### ISSUE THREAD

**Issue by meodai** [meodai/fettepalette#13]
in parcel 1.x I have to
```js
import {
  generateRandomColorRamp
} from 'fettepalette/dist/index';
```
to make it work.

in vanilla node it works fine:
```js

import {
  generateRandomColorRamp
} from 'fettepalette'
```

canvas-sketch uses browserify 
const {generateRandomColorRamp} = require('fettepalette');

only returns an empty object

**Comment by lihbr** [comment]
Hey, maybe it's due to Parcel preferring the "additional new" `exports` key, so maybe adding something like this to the package would do:
```json
"exports": {
	".": {
		"require": "./dist/index.js",
		"import": "./dist/index.esm.js"
	},
	"./package.json": "./package.json"
}
```

**Comment by meodai** [comment]
@lihbr thanks so much! I managed to fix it. I now have a build.js script that is easier to modify

**Comment by Apsysikal** [comment]
I had to fix the imports using the following additions/modifications to the `package.json` file in the `node_modules/` folder. I described it aswell in #17.

```
...,
"exports": {
    "require": "./dist/index.cjs",
    "import": "./dist/index.mjs"
},
...
```
This worked for me and I'm using it as described. Does anyone have the time to test it aswell?

**Comment by meodai** [comment]
I'm lost

**Comment by error-four-o-four** [comment]
hey there,
maybe it's worthwile to take a look at 'vite.js' which has a library mode. it really simplifies the developing and bundling process.
