### ISSUE TITLE
Consider using an enum for CurveMethod

### ISSUE THREAD

**Issue by caillou** [meodai/fettepalette#9]

**Comment by meodai** [comment]
can you educate me on the difference it makes with the type I have now? Not sure what the benefit would be.

**Comment by caillou** [comment]
My initial thought was, that you could easily iterate over the `enum` at runtime.

```typescript
enum Letters {
  A, B, C
}
console.log(
  JSON.stringify(Letters, null, 2)
);
```

I expected to get back the array of these 3 letters. Unfortunately, `enum`s don't behave the way I expected at runtime:

```json
{
  "0": "A",
  "1": "B",
  "2": "C",
  "A": 0,
  "B": 1,
  "C": 2
}
```

So consider this closed.
